global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kr-netmon-prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kr-netmon-snmp'
    static_configs:
      - targets:
        - 192.168.10.1 # Example switch
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: kr-netmon-snmp-exporter:9116
