apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web-nginx-pgsql:8080/api_jsonrpc.php
    user: Admin
    secureJsonData:
      password: zabbix
    jsonData:
      trends: true
      dbConnectionEnable: true
