apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://kr-netmon-zabbix-web:8080/api_jsonrpc.php
    jsonData:
      username: Admin
      password: ${ZABBIX_ADMIN_PASSWORD:-zabbix}
      keepCookies: []
    secureJsonData:
      password: ${ZABBIX_ADMIN_PASSWORD:-zabbix}
    editable: true
